services:
  frontend:
    image: breno-yukio/frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "7860:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: breno-yukio/backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
