services:
  gradio-service:
    image: breno-yukio/frontend
    build:
      context: gradio-json
      dockerfile: Dockerfile
    ports:
      - "7860:80"
    depends_on:
      - backend-json
    restart: unless-stopped

  backend-json:
    image: breno-yukio/backend
    build:
      context: backend-json
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
